### ISSUE TITLE
[pip] `libbbcsig.dylib` not found

### ISSUE THREAD

**Issue by ebiiim** [beyond-blockchain/bbc1#124]
I have installed the latest version of bbc1 using pip.
But `from bbc1.core import bbclib` does not work and returns an `OSError` indicating that `libbbcsig.dylib` does not exist. (I confirmed both Pipenv and venv)

```
Python 3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bbc1.core import bbclib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/{PATH_TO_PIPENV}/lib/python3.7/site-packages/bbc1/core/bbclib.py", line 33, in <module>
    import bbc1.core.libs.bbclib_utils as bbclib_utils
  File "/{PATH_TO_PIPENV}/lib/python3.7/site-packages/bbc1/core/libs/bbclib_utils.py", line 29, in <module>
    from bbc1.core.libs.bbclib_config import DEFAULT_ID_LEN
  File "/{PATH_TO_PIPENV}/lib/python3.7/site-packages/bbc1/core/libs/bbclib_config.py", line 22, in <module>
    from bbc1.core.libs.bbclib_keypair import KeyType
  File "/{PATH_TO_PIPENV}/lib/python3.7/site-packages/bbc1/core/libs/bbclib_keypair.py", line 31, in <module>
    libbbcsig = cdll.LoadLibrary(os.path.join(directory, "libbbcsig.dylib"))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/{PATH_TO_PIPENV}/lib/python3.7/site-packages/bbc1/core/libs/libbbcsig.dylib, 6): image not found
```

How can I install it successfully?

**Comment by ebiiim** [comment]
It seems like a problem with caching.
When I re-installed bbc1 with the no-cache option, it worked well.
`pip --no-cache-dir install bbc1`
Sorry to bother you.
