### ISSUE TITLE
v0.10 file_proof sample fails to get a file

### ISSUE THREAD

**Issue by ks91** [beyond-blockchain/bbc1#72]
```
$ python file_proof.py get test.txt
```
fails with the following message:
```
Traceback (most recent call last):
  File "file_proof.py", line 487, in <module>
    get_file(file=parsed_args.target_file)
  File "file_proof.py", line 263, in get_file
    ret = bbc_app_client.search_asset(asset_group_id, fileinfo["asset_id"])
AttributeError: 'BBcAppClient' object has no attribute 'search_asset'
```

**Comment by quvox** [comment]
The branch 1.0-pre fixed the problem, which is not applied to develop branch. Sorry.
